version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pwd
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: ingesta_csv
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
